export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_COURSES = 'UPDATE_COURSES';
export const UPDATE_COURSE_DETAIL = 'UPDATE_COURSE_DETAIL';
export const UPDATE_TAGS = 'UPDATE_TAGS';
export const FETCH_EXAMS = 'FETCH_EXAMS';
export const FETCH_EXAM_DETAIL = 'FETCH_EXAM_DETAIL';