export const UPDATE_USER = 'UPDATE_USER';
export const FETCH_EQUIPMENT = 'FETCH_EQUIPMENT';
export const FETCH_RESERVE = 'FETCH_RESERVE';
export const FETCH_RESERVE_DETAIL = 'FETCH_RESERVE_DETAIL';
export const FETCH_TRIP = 'FETCH_TRIP';
export const FETCH_TRIP_DETAIL = 'FETCH_TRIP_DETAIL';
export const FETCH_TRIP_URL = 'FETCH_TRIP_URL';
export const FETCH_ALL_RESERVE = 'FETCH_ALL_RESERVE';